import type { Metadata } from "next";
import { Space_Grotesk  } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/Footer/Footer";
import { ToastContainer } from 'react-toastify';
const SpaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "HELMY DEV | PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SpaceGrotesk.className} antialiased`}
      >
        <Header/>
        <ToastContainer />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
